workflows:
    android-workflow-id:
        name: Android Sample Workflow
        # .......    
        # .......
        # .......  
    ios-workflow-id:
        name: iOS Sample Workflow
        # ......
    my-workflow:
    scripts:
      - name: Launch emulator
        script: |
          set -e # exit on first failed command

          cd $ANDROID_HOME/tools
          emulator -avd emulator &
          adb wait-for-device
